/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nura;

import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class AddFrame extends javax.swing.JFrame {
  //  ArrayList <Integer> ar= new ArrayList<>();
    private JFrame parent;
    
    public AddFrame(JFrame parent) {
        initComponents(); //инициализируем элементы
        //задаем окну иконку
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getClassLoader().getResource("img/иконка.png")));
        this.parent = parent; //в MenuFrame создаем окно AddFrame(наследнкиа) и передаем ссылку на MenuFrame(родителя) в качестве параметра parent
                              //это нужно для связи окон... 
        this.setLocation(parent.getLocation()); //и отображения нового окна в том же месте, где был parent
        this.setResizable(false); //запрещаем изменение размера окна
    }
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaAdd = new javax.swing.JTextArea();
        ButAddExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ButAddBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TextAreaAddName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(249, 246, 222));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(810, 510));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/добавить1.png"))); // NOI18N
        ButAdd.setBorderPainted(false);
        ButAdd.setContentAreaFilled(false);
        ButAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAddActionPerformed(evt);
            }
        });
        jPanel1.add(ButAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 130, 40));

        TextAreaAdd.setColumns(20);
        TextAreaAdd.setRows(5);
        jScrollPane1.setViewportView(TextAreaAdd);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 69, 290, 350));

        ButAddExit.setBackground(new java.awt.Color(249, 246, 222));
        ButAddExit.setForeground(new java.awt.Color(51, 30, 24));
        ButAddExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Выход_1.png"))); // NOI18N
        ButAddExit.setBorderPainted(false);
        ButAddExit.setContentAreaFilled(false);
        ButAddExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButAddExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAddExitActionPerformed(evt);
            }
        });
        jPanel1.add(ButAddExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 130, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/записываю.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 270, 120));

        ButAddBack.setBackground(new java.awt.Color(249, 246, 222));
        ButAddBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Назад.png"))); // NOI18N
        ButAddBack.setBorderPainted(false);
        ButAddBack.setContentAreaFilled(false);
        ButAddBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButAddBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAddBackActionPerformed(evt);
            }
        });
        jPanel1.add(ButAddBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 133, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/новый_рецепт.gif"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(800, 500));
        jLabel2.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, 320));

        TextAreaAddName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAreaAddNameActionPerformed(evt);
            }
        });
        jPanel1.add(TextAreaAddName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 290, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/кухня_размытая.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButAddExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAddExitActionPerformed
        new ExitFrame(this).setVisible(true); //при нажатии на кнопку выход создаем окно(наследник) и передаем в качестве параметра ссылку на данное окно(родителя)
                                              //делаем окно-наследника видимым
        this.setVisible(false); //делаем окно-родителя невидимым
    }//GEN-LAST:event_ButAddExitActionPerformed

    private void ButAddBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAddBackActionPerformed
        parent.setVisible(true); //при нажатии на кнопку назад, родитель становится видимым
        this.setVisible(false); //а наследник невидимым
    }//GEN-LAST:event_ButAddBackActionPerformed

    private void ButAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ButAddActionPerformed
    {//GEN-HEADEREND:event_ButAddActionPerformed
       String sqls = "select max(add_id) from added_recept"; //запрос для получения максимального айдишника
        int id = Nuranew.getMaxID(sqls)+1; // текущее число максимум +1
    
        String line = null;
        String text = null;
        //берем из данных полей введенный текст
        line = TextAreaAddName.getText();  //название рецепта
        text = TextAreaAdd.getText();  //текст рецепта
       
      
        int bim = Nuranew.add_info(id, line, text); //метод класса, который работает с бд (добавление строки)
        if (bim < 1){ //если удачно, возвращается значение количества обработанных строк (в нашем случае - 1)
           JOptionPane.showMessageDialog(this, "Не удалось загрузить информацию в БД");
        } else { //если ошибка, возвращается 0
            //JOptionPane.showMessageDialog(this, "Информация о добавленном рецепте загружена в БД, ID="+id);
            //после добавления рецепта, поля очищаются
            TextAreaAddName.setText(""); 
            TextAreaAdd.setText("");
        } 
        
        
        //BufferedReader bufread = new BufferedReader();

    }//GEN-LAST:event_ButAddActionPerformed

    private void TextAreaAddNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TextAreaAddNameActionPerformed
    {//GEN-HEADEREND:event_TextAreaAddNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAreaAddNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AddFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButAdd;
    private javax.swing.JButton ButAddBack;
    private javax.swing.JButton ButAddExit;
    private javax.swing.JTextArea TextAreaAdd;
    private javax.swing.JTextField TextAreaAddName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
